[package]
name = "seedmirror-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
log.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
